name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker login
      run: |
        echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin 2>&1
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mindflavor/prometheus_sql_server_exporter:latest

    - name: Docker hub push
      run: docker push ${{secrets.DOCKER_USER}}/prometheus_sql_server_exporter:latest
